### ISSUE TITLE
Mathematical Formulation of User Equilibrium Problem

### ISSUE THREAD

**Issue by ZhengLi95** [AndreaLI95/User-Equilibrium-Solution#4]
The statement of the user equilibrium problem is contained in the [textfile](https://github.com/ZhengLi95/User-Equilibrium-Solution/blob/master/theory/user-equilibrium-solution.pdf).

The key problem is the derivation of mathematical formulation appearing in the section 3, which does not have an intuitive interpretation.

In the book [Urban Transportation Networks](http://web.mit.edu/sheffi/www/selectedMedia/sheffi_urban_trans_networks.pdf) Chapter 3.2, the author use some techniques related to Lagrangian function to derive the equivalent formulation; but my professor mentioned that it could also be derived using some techniques in Game Theory; this is what I am seeking for.

@tilltill

**Comment by tillkletti** [comment]
1. When discussing a document involving equations, it can be useful to conform to the Fisher's rule, i.e numbering all equations.
2. In the "nonintuitive" formulation section 3, you write $g_a(\omega)$ but do not define it. So I don't understand.
3. Wardrop's principle seems to be a pure Nash equilibrium.
4. In a game with finite number of players and of strategies, there always is a mixed Nash equilibrium. Perhaps all those mixed strategies correspond to "pure" $f$ configurations.

**Comment by ZhengLi95** [comment]
It should be $ p_a (\omega) $, the link performance function.. Mamma mia I should read the book of Lucchetti.. thanks a lot
