### ISSUE TITLE
Not able to input graph with bidirectional edges

### ISSUE THREAD

**Issue by uday-uppal** [AndreaLI95/User-Equilibrium-Solution#6]
For example, if 2 is in the adjacency list of 1, and 1 is in the adjacency list of 2, then it shows INDEX out of BOUNDS error. Please help with this. I want to simulate a passage where movement is allowed both ways, between 2 nodes.

**Comment by ZhengLi95** [comment]
Hi! This program does not support the case that one node is an origin and a destination at the same time. I suggest you solve the equilibrium problem by hand since you got just 2 nodes.
